use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CompileError {
    UnexpectedCharacter,
    FatalCompilerError,
    ProgramCompoundStatementAtStart,
    UnexpectedEndCompoundStatement,
    AfterCompoundStatementAtEnd,
    ParsingVariableList,
    UnknownStateInCompiler,
    InvalidDeclarationType,
    NoLeftBracketOnExpression,
    NoRightBracketOnExpression,
    BadStartOfStatement,
    NoLeftBracketOnArgList,
    NoRightBracketOnArgList,
    NoSemicolonAfterExpression,
    ParsingAssignmentStatement,
    BadLValue,
    BadConstantType,
    IdentifierListFull,
    NonIntegerIdForIntegerConstant,
    NonFloatIdForFloatConstant,
    NonStringIdForStringConstant,
    VariableAlreadyUsedWithinScope,
    VariableDefinedWithoutType,
    IncorrectVariableStateLeftOnStack,
    NonIntegerExpressionWhereIntegerRequired,
    VoidExpressionWhereNonVoidRequired,
    InvalidParametersForAssignment,
    DeclarationDoesNotMatchParameters,
    LogicalOperationHasInvalidOperands,
    EqualityTestHasInvalidOperands,
    ComparisonTestHasInvalidOperands,
    ShiftOperationHasInvalidOperands,
    ArithmeticOperationHasInvalidOperands,
    UnknownOperationInSemanticCheck,
    ScriptTooLarge,
    ReturnStatementHasNoParameters,
    NoWhileAfterDoKeyword,
    FunctionDefinitionMissingName,
    FunctionDefinitionMissingParameterList,
    MalformedParameterList,
    BadTypeSpecifier,
    NoSemicolonAfterStructure,
    EllipsisInIdentifier,
    FileNotFound,
    IncludeRecursive,
    IncludeTooManyLevels,
    ParsingReturnStatement,
    ParsingIdentifierList,
    ParsingFunctionDeclaration,
    DuplicateFunctionImplementation,
    TokenTooLong,
    UndefinedStructure,
    LeftOfStructurePartNotStructure,
    RightOfStructurePartNotFieldInStructure,
    UndefinedFieldInStructure,
    StructureRedefined,
    VariableUsedTwiceInSameStructure,
    FunctionImplementationAndDefinitionDiffer,
    MismatchedTypes,
    IntegerNotAtTopOfStack,
    ReturnTypeAndFunctionTypeMismatched,
    NotAllControlPathsReturnAValue,
    UndefinedIdentifier,
    NoFunctionMainInScript,
    FunctionMainMustHaveVoidReturnValue,
    FunctionMainMustHaveNoParameters,
    NonVoidFunctionCannotBeAStatement,
    BadVariableName,
    NonOptionalParameterCannotFollowOptionalParameter,
    TypeDoesNotHaveAnOptionalParameter,
    NonConstantInFunctionDeclaration,
    ParsingConstantVector,
    OperandMustBeAnIntegerLValue,
    ConditionalRequiresSecondExpression,
    ConditionalMustHaveMatchingReturnTypes,
    MultipleDefaultStatementsWithinSwitch,
    MultipleCaseConstantStatementsWithinSwitch,
    CaseParameterNotAConstantInteger,
    SwitchMustEvaluateToAnInteger,
    NoColonAfterDefaultLabel,
    NoColonAfterCaseLabel,
    NoSemicolonAfterStatement,
    BreakOutsideOfLoopOrCaseStatement,
    TooManyParametersOnFunction,
    UnableToOpenFileForWriting,
    UnterminatedStringConstant,
    NoFunctionIntscInScript,
    FunctionIntscMustHaveVoidReturnValue,
    FunctionIntscMustHaveNoParameters,
    JumpingOverDeclarationStatementsCaseDisallowed,
    JumpingOverDeclarationStatementsDefaultDisallowed,
    ElseWithoutCorrespondingIf,
    IfConditionCannotBeFollowedByNullStatement,
    InvalidTypeForConstKeyword,
    ConstKeywordCannotBeUsedOnNonGlobalVariables,
    InvalidValueAssignedToConstant,
    SwitchConditionCannotBeFollowedByNullStatement,
    WhileConditionCannotBeFollowedByNullStatement,
    ForStatementCannotBeFollowedByNullStatement,
    CannotIncludeThisFileTwice,
    ElseCannotBeFollowedByNullStatement,
    AlreadyPrinted,
}

impl CompileError {
    pub fn strref(self) -> i32 {
        match self {
            Self::UnexpectedCharacter => -560,
            Self::FatalCompilerError => -561,
            Self::ProgramCompoundStatementAtStart => -562,
            Self::UnexpectedEndCompoundStatement => -563,
            Self::AfterCompoundStatementAtEnd => -564,
            Self::ParsingVariableList => -565,
            Self::UnknownStateInCompiler => -566,
            Self::InvalidDeclarationType => -567,
            Self::NoLeftBracketOnExpression => -568,
            Self::NoRightBracketOnExpression => -569,
            Self::BadStartOfStatement => -570,
            Self::NoLeftBracketOnArgList => -571,
            Self::NoRightBracketOnArgList => -572,
            Self::NoSemicolonAfterExpression => -573,
            Self::ParsingAssignmentStatement => -574,
            Self::BadLValue => -575,
            Self::BadConstantType => -576,
            Self::IdentifierListFull => -577,
            Self::NonIntegerIdForIntegerConstant => -578,
            Self::NonFloatIdForFloatConstant => -579,
            Self::NonStringIdForStringConstant => -580,
            Self::VariableAlreadyUsedWithinScope => -581,
            Self::VariableDefinedWithoutType => -582,
            Self::IncorrectVariableStateLeftOnStack => -583,
            Self::NonIntegerExpressionWhereIntegerRequired => -584,
            Self::VoidExpressionWhereNonVoidRequired => -585,
            Self::InvalidParametersForAssignment => -586,
            Self::DeclarationDoesNotMatchParameters => -587,
            Self::LogicalOperationHasInvalidOperands => -588,
            Self::EqualityTestHasInvalidOperands => -589,
            Self::ComparisonTestHasInvalidOperands => -590,
            Self::ShiftOperationHasInvalidOperands => -591,
            Self::ArithmeticOperationHasInvalidOperands => -592,
            Self::UnknownOperationInSemanticCheck => -593,
            Self::ScriptTooLarge => -594,
            Self::ReturnStatementHasNoParameters => -595,
            Self::NoWhileAfterDoKeyword => -596,
            Self::FunctionDefinitionMissingName => -597,
            Self::FunctionDefinitionMissingParameterList => -598,
            Self::MalformedParameterList => -599,
            Self::BadTypeSpecifier => -600,
            Self::NoSemicolonAfterStructure => -601,
            Self::EllipsisInIdentifier => -602,
            Self::FileNotFound => -603,
            Self::IncludeRecursive => -604,
            Self::IncludeTooManyLevels => -605,
            Self::ParsingReturnStatement => -606,
            Self::ParsingIdentifierList => -607,
            Self::ParsingFunctionDeclaration => -608,
            Self::DuplicateFunctionImplementation => -609,
            Self::TokenTooLong => -610,
            Self::UndefinedStructure => -611,
            Self::LeftOfStructurePartNotStructure => -612,
            Self::RightOfStructurePartNotFieldInStructure => -613,
            Self::UndefinedFieldInStructure => -614,
            Self::StructureRedefined => -615,
            Self::VariableUsedTwiceInSameStructure => -616,
            Self::FunctionImplementationAndDefinitionDiffer => -617,
            Self::MismatchedTypes => -618,
            Self::IntegerNotAtTopOfStack => -619,
            Self::ReturnTypeAndFunctionTypeMismatched => -620,
            Self::NotAllControlPathsReturnAValue => -621,
            Self::UndefinedIdentifier => -622,
            Self::NoFunctionMainInScript => -623,
            Self::FunctionMainMustHaveVoidReturnValue => -624,
            Self::FunctionMainMustHaveNoParameters => -625,
            Self::NonVoidFunctionCannotBeAStatement => -626,
            Self::BadVariableName => -627,
            Self::NonOptionalParameterCannotFollowOptionalParameter => -628,
            Self::TypeDoesNotHaveAnOptionalParameter => -629,
            Self::NonConstantInFunctionDeclaration => -630,
            Self::ParsingConstantVector => -631,
            Self::OperandMustBeAnIntegerLValue => -1594,
            Self::ConditionalRequiresSecondExpression => -1595,
            Self::ConditionalMustHaveMatchingReturnTypes => -1596,
            Self::MultipleDefaultStatementsWithinSwitch => -1597,
            Self::MultipleCaseConstantStatementsWithinSwitch => -1598,
            Self::CaseParameterNotAConstantInteger => -1599,
            Self::SwitchMustEvaluateToAnInteger => -1600,
            Self::NoColonAfterDefaultLabel => -1601,
            Self::NoColonAfterCaseLabel => -1602,
            Self::NoSemicolonAfterStatement => -1603,
            Self::BreakOutsideOfLoopOrCaseStatement => -4834,
            Self::TooManyParametersOnFunction => -4835,
            Self::UnableToOpenFileForWriting => -4836,
            Self::UnterminatedStringConstant => -4855,
            Self::NoFunctionIntscInScript => -5182,
            Self::FunctionIntscMustHaveVoidReturnValue => -5183,
            Self::FunctionIntscMustHaveNoParameters => -5184,
            Self::JumpingOverDeclarationStatementsCaseDisallowed => -6804,
            Self::JumpingOverDeclarationStatementsDefaultDisallowed => -6805,
            Self::ElseWithoutCorrespondingIf => -6823,
            Self::IfConditionCannotBeFollowedByNullStatement => -10407,
            Self::InvalidTypeForConstKeyword => -3741,
            Self::ConstKeywordCannotBeUsedOnNonGlobalVariables => -3742,
            Self::InvalidValueAssignedToConstant => -3752,
            Self::SwitchConditionCannotBeFollowedByNullStatement => -9081,
            Self::WhileConditionCannotBeFollowedByNullStatement => -9082,
            Self::ForStatementCannotBeFollowedByNullStatement => -9083,
            Self::CannotIncludeThisFileTwice => -9155,
            Self::ElseCannotBeFollowedByNullStatement => -40104,
            Self::AlreadyPrinted => -1,
        }
    }

    pub fn message(self) -> &'static str {
        match self {
            Self::UnexpectedCharacter => "Unexpected character",
            Self::FatalCompilerError => "Fatal compiler error",
            Self::ProgramCompoundStatementAtStart => "Expected compound statement at start of program",
            Self::UnexpectedEndCompoundStatement => "Unexpected end of compound statement",
            Self::AfterCompoundStatementAtEnd => "Unexpected token after end of program",
            Self::ParsingVariableList => "Error parsing variable list",
            Self::UnknownStateInCompiler => "Unknown state in compiler",
            Self::InvalidDeclarationType => "Invalid declaration type",
            Self::NoLeftBracketOnExpression => "Expected '(' in expression",
            Self::NoRightBracketOnExpression => "Expected ')' in expression",
            Self::BadStartOfStatement => "Bad start of statement",
            Self::NoLeftBracketOnArgList => "Expected '(' before argument list",
            Self::NoRightBracketOnArgList => "Expected ')' after argument list",
            Self::NoSemicolonAfterExpression => "Expected ';' after expression",
            Self::ParsingAssignmentStatement => "Error parsing assignment statement",
            Self::BadLValue => "Invalid l-value in assignment",
            Self::BadConstantType => "Bad constant type",
            Self::IdentifierListFull => "Identifier list is full",
            Self::NonIntegerIdForIntegerConstant => "Non-integer identifier used for integer constant",
            Self::NonFloatIdForFloatConstant => "Non-float identifier used for float constant",
            Self::NonStringIdForStringConstant => "Non-string identifier used for string constant",
            Self::VariableAlreadyUsedWithinScope => "Variable already used within this scope",
            Self::VariableDefinedWithoutType => "Variable defined without a type",
            Self::IncorrectVariableStateLeftOnStack => "Incorrect variable state left on stack",
            Self::NonIntegerExpressionWhereIntegerRequired => "Non-integer expression where integer required",
            Self::VoidExpressionWhereNonVoidRequired => "Void expression where non-void required",
            Self::InvalidParametersForAssignment => "Invalid parameters for assignment",
            Self::DeclarationDoesNotMatchParameters => "Declaration does not match parameters",
            Self::LogicalOperationHasInvalidOperands => "Logical operation has invalid operands",
            Self::EqualityTestHasInvalidOperands => "Equality test has invalid operands",
            Self::ComparisonTestHasInvalidOperands => "Comparison test has invalid operands",
            Self::ShiftOperationHasInvalidOperands => "Shift operation has invalid operands",
            Self::ArithmeticOperationHasInvalidOperands => "Arithmetic operation has invalid operands",
            Self::UnknownOperationInSemanticCheck => "Unknown operation in semantic check",
            Self::ScriptTooLarge => "Script too large",
            Self::ReturnStatementHasNoParameters => "Return statement has no parameters",
            Self::NoWhileAfterDoKeyword => "Expected 'while' after 'do' block",
            Self::FunctionDefinitionMissingName => "Function definition missing name",
            Self::FunctionDefinitionMissingParameterList => "Function definition missing parameter list",
            Self::MalformedParameterList => "Malformed parameter list",
            Self::BadTypeSpecifier => "Bad type specifier",
            Self::NoSemicolonAfterStructure => "Expected ';' after structure definition",
            Self::EllipsisInIdentifier => "Ellipsis in identifier",
            Self::FileNotFound => "File not found",
            Self::IncludeRecursive => "Recursive include detected",
            Self::IncludeTooManyLevels => "Too many include levels",
            Self::ParsingReturnStatement => "Error parsing return statement",
            Self::ParsingIdentifierList => "Error parsing identifier list",
            Self::ParsingFunctionDeclaration => "Error parsing function declaration",
            Self::DuplicateFunctionImplementation => "Duplicate function implementation",
            Self::TokenTooLong => "Token too long",
            Self::UndefinedStructure => "Undefined structure",
            Self::LeftOfStructurePartNotStructure => "Left side of '.' is not a structure",
            Self::RightOfStructurePartNotFieldInStructure => "Right side of '.' is not a field in the structure",
            Self::UndefinedFieldInStructure => "Undefined field in structure",
            Self::StructureRedefined => "Structure redefined",
            Self::VariableUsedTwiceInSameStructure => "Variable used twice in the same structure",
            Self::FunctionImplementationAndDefinitionDiffer => "Function implementation and definition differ",
            Self::MismatchedTypes => "Mismatched types",
            Self::IntegerNotAtTopOfStack => "Integer not at top of stack",
            Self::ReturnTypeAndFunctionTypeMismatched => "Return type and function type mismatched",
            Self::NotAllControlPathsReturnAValue => "Not all control paths return a value",
            Self::UndefinedIdentifier => "Undefined identifier",
            Self::NoFunctionMainInScript => "No 'void main()' function in script",
            Self::FunctionMainMustHaveVoidReturnValue => "'main' must have void return value",
            Self::FunctionMainMustHaveNoParameters => "'main' must have no parameters",
            Self::NonVoidFunctionCannotBeAStatement => "Non-void function cannot be used as a statement",
            Self::BadVariableName => "Bad variable name",
            Self::NonOptionalParameterCannotFollowOptionalParameter => "Non-optional parameter cannot follow optional parameter",
            Self::TypeDoesNotHaveAnOptionalParameter => "Type does not have an optional parameter",
            Self::NonConstantInFunctionDeclaration => "Non-constant value in function declaration",
            Self::ParsingConstantVector => "Error parsing constant vector",
            Self::OperandMustBeAnIntegerLValue => "Operand must be an integer l-value",
            Self::ConditionalRequiresSecondExpression => "Conditional operator requires second expression",
            Self::ConditionalMustHaveMatchingReturnTypes => "Conditional expressions must have matching return types",
            Self::MultipleDefaultStatementsWithinSwitch => "Multiple default statements within switch",
            Self::MultipleCaseConstantStatementsWithinSwitch => "Multiple case statements with the same constant within switch",
            Self::CaseParameterNotAConstantInteger => "Case parameter is not a constant integer",
            Self::SwitchMustEvaluateToAnInteger => "Switch expression must evaluate to an integer",
            Self::NoColonAfterDefaultLabel => "Expected ':' after default label",
            Self::NoColonAfterCaseLabel => "Expected ':' after case label",
            Self::NoSemicolonAfterStatement => "Expected ';' after statement",
            Self::BreakOutsideOfLoopOrCaseStatement => "Break outside of loop or case statement",
            Self::TooManyParametersOnFunction => "Too many parameters on function",
            Self::UnableToOpenFileForWriting => "Unable to open file for writing",
            Self::UnterminatedStringConstant => "Unterminated string constant",
            Self::NoFunctionIntscInScript => "No 'int StartingConditional()' function in script",
            Self::FunctionIntscMustHaveVoidReturnValue => "'StartingConditional' must have int return value",
            Self::FunctionIntscMustHaveNoParameters => "'StartingConditional' must have no parameters",
            Self::JumpingOverDeclarationStatementsCaseDisallowed => "Jumping over declaration in case is disallowed",
            Self::JumpingOverDeclarationStatementsDefaultDisallowed => "Jumping over declaration in default is disallowed",
            Self::ElseWithoutCorrespondingIf => "'else' without corresponding 'if'",
            Self::IfConditionCannotBeFollowedByNullStatement => "'if' condition cannot be followed by null statement",
            Self::InvalidTypeForConstKeyword => "Invalid type for const keyword",
            Self::ConstKeywordCannotBeUsedOnNonGlobalVariables => "const keyword can only be used on global variables",
            Self::InvalidValueAssignedToConstant => "Invalid value assigned to constant",
            Self::SwitchConditionCannotBeFollowedByNullStatement => "'switch' condition cannot be followed by null statement",
            Self::WhileConditionCannotBeFollowedByNullStatement => "'while' condition cannot be followed by null statement",
            Self::ForStatementCannotBeFollowedByNullStatement => "'for' statement cannot be followed by null statement",
            Self::CannotIncludeThisFileTwice => "Cannot include this file twice",
            Self::ElseCannotBeFollowedByNullStatement => "'else' cannot be followed by null statement",
            Self::AlreadyPrinted => "",
        }
    }
}

impl fmt::Display for CompileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message())
    }
}

#[derive(Debug, Clone)]
pub struct Diagnostic {
    pub error: CompileError,
    pub file: String,
    pub line: u32,
    pub message: String,
}

impl fmt::Display for Diagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({}): ERROR: {}", self.file, self.line, self.message)
    }
}
